apiVersion: apps/v1
kind: Deployment
metadata:
  name: btech-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: btech
  template:
    metadata:
      labels:
        app: btech
    spec:
      containers:
      - name: btech
        image: btech:1.0
        ports:
        - containerPort: 3000